# Site Settings
title: ShowChat
email: showchat.ro@gmail.com
description: >
  Comunitatea ShowChat Romania chat online
baseurl: "/"
url: "https://showchat.tk"
twitter_username: showchat.ro
github_username:  show-chat
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

  # generate social links in footer
  social_links:
    twitter: showchat.ro
    github:  show-chat
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
