# Site Settings
title: ShowChat
email: showchat.ro@gmail.com
description: >
  Comunitatea ShowChat Romania chat online
author: ShowChat.TK
baseurl: "/"
url: "https://showchat.tk"
twitter_username: showchat.ro
github_username:  show-chat
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
